### ISSUE TITLE
Add analytics tracking inside the CMS

### ISSUE THREAD

**Issue by thibaudcolas** [wagtail/madewithwagtail#75]
In the quest to improve Wagtail as a CMS, we have a big information gap between what features are available to users and what's actually used. We've been having conversations about doing more user testing, and also potentially having some sort of tracking of interactions with the CMS.

I'd like to trial this on this project. It's probably not the most representative in terms of site usage, but since it's open source and only meant for the Wagtail community I'm less concerned about privacy and secrecy issues.

Here is a proposed course of action:

- [ ] Find a good disclaimer text informing users that there is analytics tracking enabled.
- [ ] Find a prominent place to add the disclaimer, and add it there.
- [ ] Add the default Google Analytics tracking.
- [ ] Consider more refined tagging, either via custom JS, custom HTML (à la `springload-analytics.js`, or GTM.
- [ ] Set up once-a-month catch-ups/reports to see what the numbers look like.

Things I'm not too sure of:

- Whether it is good to implement tracking opt-out (for the purpose of this experiment)
- Whether the page views should be anonymised to some extent (with our move towards accounts for every dev, it will be very easy to associate specific interactions on given pages with a person)
- Whether this should be tracked on the same GA account as the site's front-end, or not. 

Things this could help answer (likely with caveats):

- Are people using the "Page lock" feature?
- Do people navigate the site with the explorer menu, or explorer pages?
- Is the search useful?
- How much time is spent on every part of the editing workflow (and what we should look at to lower it)
- What features should we prioritise work on in Wagtail?
- Do updates to the CMS actually make it better and help decrease staff time devoted to CMS editing?
- Should we put a bigger emphasis on support for mobile devices?

**Comment by thibaudcolas** [comment]
Hey @jennyadamsnz, if you have time could you look at this? I would be interested to try out adding the tracking _inside_ Wagtail, but haven't had any time to investigate how to do it.

Note that this task would require quite a bit of investigation to understand how best to add the GA snippet to the Wagtail admin templates.
